# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8c60501cb9f9f8f2292ac7aff06d3b23f398d8b598a482f5c13441f0885c82303b54f2d9ead8722864103424e491b69b3e592d7de0f1df5d44b1100faed3e5e8

test:
  secret_key_base: b37c27230fc17dd97142bd6e0f325cb2cdd16d0e4c7660d3af315c16d94faa5a86cf35e0fceff536f116109086696034860e88cdd726ed3609231f91f5a6fc62

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
